### ISSUE TITLE
Hetmech logo

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/hetmech-frontend#14]
It's logo time again. This is all I could come up with that was reasonably good. Cast your votes or make your suggestions:

https://jsfiddle.net/evbg4aht/show

**Comment by dhimmel** [comment]
Proposed logo looks really nice at many scales:

![image](https://user-images.githubusercontent.com/1117703/55801548-4f1dcc00-5aa4-11e9-9a47-b928baafacc5.png)

The DNA appears to be right-handed which is the [natural conformation](https://sandwalk.blogspot.com/2015/03/on-handedness-of-dna.html). I am a bit worried that a DNA-based logo is inappropriate since DNA and the genome is not directly an aspect of hetmech. While in general people may associate DNA with science, I think within our userbase, it could be a bit misleading.

What I'm thinking we really want to capture are:

+ hetnets
+ paths through hetnets
+ analysis or computation on hetnets

**Comment by ben-heil** [comment]
I agree that more graph inspired logos are probably better than DNA inspired ones since most of the features in the database aren't directly DNA related. My favorite is logo 7, background (18, 0), text color (17, 13).

I really like how logo 7 conveys both that there are different types of nodes and that they are connected to different things.

**Comment by cgreene** [comment]
I like lots of them! I'm a little partial to 9 since it feels like it captures a path, but I like lots of them 👍

**Comment by dongbohu** [comment]
I don't have a strong preference either. I like 3 and 5 slightly more than I do the others.

**Comment by vincerubinetti** [comment]
Second round, shortlist:

https://jsfiddle.net/dcj9L5pk/show

#1 is a new contender. But I'm still leaning toward #2 for the following reasons:
- the other graph ones are fairly generic. #4 looks like it could be for a plotting software like MS Excel, and #5 just looks very basic. #3 looks cool, but that triangle formation has most likely been done before.
- the asterisk in #2 has associations with [general health](https://www.google.com/search?q=health+symbol&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjYvJnZ9sXhAhXwuFkKHRL4DuwQ_AUIDigB&biw=956&bih=680) and [medicine](https://www.google.com/search?biw=956&bih=680&tbm=isch&sa=1&ei=UBeuXKjVEoaRggeRtJTwBw&q=medical+symbol&oq=medical+symbol&gs_l=img.3..35i39j0l9.4468.4919..5062...0.0..0.64.420.7......1....1..gws-wiz-img.......0i67j0i7i30.-D9uxTiJPUA). it also has the double meaning of "importance", which is one of the things this product does: attempt to find the most "important" paths.
- #1 is possibly the most unique and memorable of the bunch.

@dhimmel thoughts and final decision?

**Comment by cgreene** [comment]
Without the DNA bases, I am coming around to 1. Is it meant to evoke the letter H?

**Comment by vincerubinetti** [comment]
> Without the DNA bases, I am coming around to 1. Is it meant to evoke the letter H?

Now that you say that, yes, it is

**Comment by dhimmel** [comment]
Use the new numbers from https://jsfiddle.net/dcj9L5pk/show, my favorite two are:

Logo 4:

> ![image](https://user-images.githubusercontent.com/1117703/55899199-3be92a00-5b92-11e9-8e7f-6178162626cd.png)

Logo 2:

> ![image](https://user-images.githubusercontent.com/1117703/55899246-528f8100-5b92-11e9-9e14-8fd5c8f77320.png)

I think Logo 4 captures the utility of hetmech the most: finding how two nodes are connected by paths. Logo 2 is aesthetically pleasing. Do others have any feelings about 4 versus 2?

**Comment by vincerubinetti** [comment]
Two more:

![image](https://user-images.githubusercontent.com/8326331/55962700-6b09a500-5c3f-11e9-978d-652ac275f0e9.png)

![image](https://user-images.githubusercontent.com/8326331/55962709-7230b300-5c3f-11e9-8b0f-9c6171c7caa9.png)

**Comment by zietzm** [comment]
Logos 3 and 4 are my favorites

**Comment by vincerubinetti** [comment]
Also did an in-person vote with the people in the office, and the `-v^-` logo seems to be the winner over the `/*\` logo. The winner is a more banal and generic (could be any kind of graphing), but it is more descriptive of what hetmech actually is. I like the `/*\` a lot, but [we can always use it for something else in the future](https://github.com/greenelab/unused-assets/tree/master/logos).
