### ISSUE TITLE
Create webpage build content that is optimized for git tracking

### ISSUE THREAD

**Issue by dhimmel** [greenelab/hetmech-frontend#6]
Currently our `npm run build` output [on gh-pages](https://github.com/greenelab/hetmech-frontend/tree/d9ea75dcde04f3184300d936976e3365d6841b7e) is minified and does not have stable file names across changes.

This can be problematic for git tracking:

1. everytime there is a new deployment, all the blobs on gh-pages must be rewritten
2. there are not clear diffs that allow us to check that source code changes create the desired HTML changes

@arielsvn and I dealt with this issue for the Sci-Hub Stats Browser frontend. Ariel's code is [here](https://github.com/greenelab/scihub/tree/9280e4479fbe32a48d7c0f836b9292b0e4a5319c/webapp).

@vincerubinetti how hard would it be for us to include newlines and have stable filenames in the `build` output?

**Comment by arielsvn** [comment]
IMO it's better how it's implemented here, since the generated files live separated from the source code, minified and with the hashes in the filenames.

> there are not clear diffs that allow us to check that source code changes create the desired HTML changes

Is this really important? everything in gh-pages depends on the source code, checking those diffs should be enough. For example in [refinebio-frontend](https://github.com/AlexsLemonade/refinebio-frontend) we deploy to S3 and replace all files on every deploy.

When we implemented the Sci-Hub Stats Browser I wasn't aware of CircleCi and how easy it was to create a script that deployed to gh-pages automatically, that's why the generated files were included along with the source code which later created problems when reviewing the PR.

**Comment by vincerubinetti** [comment]
@dongbohu and I discussed this at length when starting the project. He argued that `react-scripts` was much easier to set up than manually configuring webpack, which is true. But if you ever need to change something about how the `react-scripts` build process works, it seems to be prohibitively difficult.

The times I've done manual webpack configuration, it did take some time upfront to set up, but after that I never had to touch it again. I could've just gotten lucky though. I think for now I might want to go back to a manual configuration, just so we have more control over (and more importantly, understanding of) the build process. If we ever wanted to go back to `react-scripts` for some reason, I think that would probably be pretty easy anyway.

**Comment by arielsvn** [comment]
Yes, `react-scripts` it's definitely not for all projects. In the case of refine.bio, we have had a good experience with it and so far we haven't ejected webpack configuration. It's good to know that's an option if we ever need it.

**Comment by vincerubinetti** [comment]
@dhimmel I previously said I was going to do a config from scratch. I'm going to take that back, because I forgot that `create-react-app` ("react scripts") automatically sets up hot-reloading, which is extremely useful during development and a huge pain to set up manually. If it were just the compiling and the bundling, I'd have already set it up myself.

Note that the output of this stuff is mostly going to be javascript, not html. And it's going to be much less readable and meaningful than the input `/src`. Someone should look at the `/src` diff to really see what has changed, as that is the true "markdown" of the content of the page. 

Recommend we close this issue, and let another one be created if we ever need to do a manual config (or a `create-react-app` eject) for a different reason.

**Comment by dhimmel** [comment]
Okay closing. We can always revisit this and reopen should the calculus change.
